# Generated by Django 5.1.3 on 2024-12-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
    ]
