# Generated by Django 5.1.3 on 2024-12-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_chat_overall_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='overall_score',
        ),
    ]
